import pickle
import hashlib
from sentence_transformers import SentenceTransformer

# ─────────────────────────────────────────────────────────────────────────────
# LEAVE REASON MASTER DATA  (sourced from updated category/reason tables)
# ─────────────────────────────────────────────────────────────────────────────
LEAVE_REASON_DATA: dict[int, dict] = {

    1: {
        "name": "MARRIAGE",
        "reasons": [
            {"id": 1,  "text": "SISTER'S MARRIAGE"},
            {"id": 2,  "text": "BROTHER'S MARRIAGE"},
            {"id": 3,  "text": "RELATIVE'S MARRIAGE"},
            {"id": 4,  "text": "COUSIN'S MARRIAGE"},
            {"id": 5,  "text": "FRIEND'S MARRIAGE"},
            {"id": 7,  "text": "OWN MARRIAGE"},
            {"id": 8,  "text": "NEPHEW'S MARRIAGE"},
            {"id": 9,  "text": "TO PURCHASE GOLD FOR MY MARRIAGE"},
            {"id": 10, "text": "SON'S MARRIAGE"},
            {"id": 11, "text": "MARRIAGE OF MY SON"},
            {"id": 12, "text": "OWN MARRIAGE RECEPTION"},
            {"id": 13, "text": "TO ATTEND MARRIAGE RECEPTION AT TRIVANDRUM"},
            {"id": 14, "text": "ATTENDED MARRIAGE IN KANNUR"},
        ],
    },

    2: {
        "name": "DEATH / BEREAVEMENT",
        "reasons": [
            {"id": 1,  "text": "RELATIVE EXPIRED"},
            {"id": 2,  "text": "FATHER EXPIRED"},
            {"id": 3,  "text": "MOTHER EXPIRED"},
            {"id": 4,  "text": "FATHER IN LAW EXPIRED"},
            {"id": 5,  "text": "MOTHER IN LAW EXPIRED"},
            {"id": 6,  "text": "GRANDFATHER EXPIRED"},
            {"id": 7,  "text": "GRANDMOTHER EXPIRED"},
            {"id": 8,  "text": "AUNT EXPIRED"},
            {"id": 9,  "text": "LAST RITES"},
            {"id": 10, "text": "UNCLE EXPIRED"},
            {"id": 11, "text": "BROTHER IN LAW EXPIRED"},
            {"id": 12, "text": "VERY CLOSE RELATIVE EXPIRED"},
            {"id": 13, "text": "COUSIN EXPIRED"},
            {"id": 14, "text": "SANJAYANAM OF FATHER"},
            {"id": 15, "text": "ADIYANTHIRAM OF FATHER"},
            {"id": 16, "text": "SISTER EXPIRED"},
            {"id": 17, "text": "11TH DAY OF SISTERS DEATH"},
            {"id": 18, "text": "HUSBAND EXPIRED"},
            {"id": 19, "text": "HUSBAND DEATH CEREMONY"},
            {"id": 20, "text": "FRIENDS FATHER EXPIRED"},
            {"id": 21, "text": "SISTER-IN-LAW EXPIRED"},
            {"id": 22, "text": "BROTHER EXPIRED"},
            {"id": 23, "text": "SANJAYANAM"},
            {"id": 24, "text": "CHILD EXPIRED"},
            {"id": 25, "text": "ADIYANTHIRAM OF MOTHER"},
            {"id": 26, "text": "41st Day of Mother's Death"},
            {"id": 27, "text": "NEIGHBOR'S DEATH"},
        ],
    },

    3: {
        "name": "FAMILY FUNCTION",
        "reasons": [
            {"id": 1,  "text": "HOUSE WARMING"},
            {"id": 2,  "text": "BIRTHDAY"},
            {"id": 3,  "text": "NAMING CEREMONY OF SON/DAUGHTER"},
            {"id": 4,  "text": "ANNAPRASAM"},
            {"id": 5,  "text": "CHILD'S BIRTHDAY"},
            {"id": 6,  "text": "GET TOGETHER"},
            {"id": 7,  "text": "CHILD'S FIRST BIRTHDAY"},
            {"id": 8,  "text": "FAMILY FUNCTION"},
            {"id": 9,  "text": "SISTERS DAUGHTER'S 1ST BIRTHDAY"},
            {"id": 10, "text": "PRE DELIVERY FUNCTION"},
            {"id": 11, "text": "KETTUNIRA AT HOME"},
            {"id": 12, "text": "SISTER'S SON NAMING CEREMONY"},
            {"id": 13, "text": "ATTEND THE NIECE'S MARRIAGE AT HYD"},
            {"id": 14, "text": "SHASTIPOORTHI OF CO-BROTHER"},
            {"id": 15, "text": "ANNAPRASAM OF SON"},
            {"id": 16, "text": "BROTHER DAUGHTER MATURED"},
            {"id": 17, "text": "BAPTISM OF CHILD"},
            {"id": 18, "text": "NAMING CEREMONY OF GRANDSON"},
            {"id": 19, "text": "OWN HOUSE WARMING"},
            {"id": 20, "text": "GRAND SON'S BIRTH DAY"},
            {"id": 21, "text": "FIRST HOLY COMMUNION"},
            {"id": 22, "text": "Wedding Anniversary"},
            {"id": 23, "text": "Family Function"},
            {"id": 24, "text": "MARRIAGE OF NEPHEW"},
        ],
    },

    4: {
        "name": "ANNIVERSARY",
        "reasons": [
            {"id": 1, "text": "DEATH ANNIVERSARY"},
            {"id": 2, "text": "MARRIAGE ANNIVERSARY"},
            {"id": 3, "text": "FIRST DEATH ANNIVERSARY OF FATHER IN LAW"},
        ],
    },

    5: {
        "name": "DISEASE",
        "reasons": [
            {"id": 1,  "text": "FEVER"},
            {"id": 2,  "text": "HEADACHE"},
            {"id": 3,  "text": "STOMACH PAIN"},
            {"id": 4,  "text": "BACK PAIN"},
            {"id": 5,  "text": "LEG PAIN"},
            {"id": 6,  "text": "EYE PAIN"},
            {"id": 7,  "text": "EAR PAIN"},
            {"id": 8,  "text": "CHEST PAIN"},
            {"id": 9,  "text": "DYSENTERY"},
            {"id": 10, "text": "JAUNDICE"},
            {"id": 11, "text": "GIDDINESS / DIZZINESS"},
            {"id": 12, "text": "VIRAL FEVER"},
            {"id": 13, "text": "VOMITTING"},
            {"id": 14, "text": "MATERNITY"},
            {"id": 15, "text": "BED REST"},
            {"id": 16, "text": "CHICKENPOX"},
            {"id": 17, "text": "ILLNESS OF FATHER"},
            {"id": 18, "text": "ILLNESS OF MOTHER"},
            {"id": 19, "text": "ILLNESS OF HUSBAND"},
            {"id": 20, "text": "ILLNESS OF CHILD"},
            {"id": 21, "text": "ILLNESS OF FATHER IN LAW"},
            {"id": 22, "text": "ILLNESS OF MOTHER IN LAW"},
            {"id": 23, "text": "MEDICAL CHECK UP"},
            {"id": 24, "text": "ILLNESS OF WIFE"},
            {"id": 25, "text": "CONSULT DOCTOR"},
            {"id": 26, "text": "ILLNESS OF BROTHER IN LAW"},
            {"id": 27, "text": "ILLNESS OF SISTER IN LAW"},
            {"id": 28, "text": "ACCIDENT"},
            {"id": 29, "text": "ASTHMA"},
            {"id": 30, "text": "CHILD HOSPITALISED"},
            {"id": 31, "text": "CHILD'S VACCINATION"},
            {"id": 32, "text": "APPOINTMENT WITH DOCTOR FOR MEDICAL CHECK UP"},
            {"id": 33, "text": "MINOR ACCIDENT"},
            {"id": 34, "text": "WIFE HOSPITALISED"},
            {"id": 35, "text": "URINARY INFECTION"},
            {"id": 36, "text": "ACCOMPANY HUSBAND TO HOSPITAL FOR MEDICAL CHECKUP"},
            {"id": 37, "text": "LOW B.P"},
            {"id": 38, "text": "BACK PAIN DUE TO OVARIAN CYST"},
            {"id": 39, "text": "PRE SURGERY TEST"},
            {"id": 40, "text": "EYE INFECTION"},
            {"id": 41, "text": "CLOSE RELATIVE OPERATION"},
            {"id": 42, "text": "Measles Of Child"},
            {"id": 43, "text": "OPERATION OF MY MOTHER"},
            {"id": 44, "text": "SKIN INFECTION"},
            {"id": 45, "text": "EYE SURGERY OF WIFE"},
            {"id": 46, "text": "HUSBAND HOSPITALIZED"},
            {"id": 47, "text": "HUSBAND'S OPERATION"},
            {"id": 48, "text": "TEETH PAIN"},
            {"id": 49, "text": "BYPASS OPERATION"},
            {"id": 50, "text": "EYE SURGERY OF FATHER"},
            {"id": 51, "text": "Period Pain"},
        ],
    },

    6: {
        "name": "OTHERS",
        "reasons": [
            {"id": 1,   "text": "GO TO HUSBAND'S HOME AT KASARGOD"},
            {"id": 2,   "text": "PILGRIMAGE"},
            {"id": 4,   "text": "GO TO UNIVERSITY"},
            {"id": 5,   "text": "EXAMINATION"},
            {"id": 6,   "text": "VAVUBALI"},
            {"id": 7,   "text": "GO TO BANGALORE"},
            {"id": 8,   "text": "OTHER REASON"},
            {"id": 9,   "text": "TO PURCHASE GOLD"},
            {"id": 10,  "text": "SANJAYANAM: UNCLE'S DEATH"},
            {"id": 12,  "text": "16TH DAY ADIYANTHIRAM & MRITHYUNJAYA HOMAM"},
            {"id": 13,  "text": "GRANDMOTHER HOSPITALISED"},
            {"id": 14,  "text": "FLOOD"},
            {"id": 15,  "text": "M.M.R. VACCINATION OF CHILD"},
            {"id": 19,  "text": "REGISTRATION FOR JPHN COURSE"},
            {"id": 21,  "text": "TRANSFER FROM HYDERABAD TO COIMBATORE"},
            {"id": 22,  "text": "VARAMAHALAXMI POOJA IN HOME"},
            {"id": 24,  "text": "PERSONAL REASON"},
            {"id": 26,  "text": "PROPERTY REGISTRATION"},
            {"id": 27,  "text": "SICKNESS OF CHILD"},
            {"id": 28,  "text": "ATTEND PRE-MARRIAGE COURSE"},
            {"id": 30,  "text": "GRANDFATHER HOSPITALISED"},
            {"id": 31,  "text": "DOCTOR'S CONSULTATION OF MY SON"},
            {"id": 32,  "text": "FAMILY FUNCTION"},
            {"id": 33,  "text": "ACCOMPANYING FATHER TO APPEAR BEFORE COURT"},
            {"id": 35,  "text": "SISTER HOSPITALISED"},
            {"id": 36,  "text": "FATHER HOSPITALISED"},
            {"id": 37,  "text": "HOSPITALISED"},
            {"id": 38,  "text": "WENT TO HOSPITAL"},
            {"id": 39,  "text": "DEATH ANNIVERSARY OF MOTHER (SRADHAM)"},
            {"id": 40,  "text": "BROTHER HOSPITALISED"},
            {"id": 41,  "text": "HUSBAND CAME FROM ABROAD"},
            {"id": 42,  "text": "GO TO POST OFFICE FOR CASH WITHDRAWAL"},
            {"id": 43,  "text": "TO OPEN BANK ACCOUNT AT KOCHI"},
            {"id": 44,  "text": "FATHERS AFTER DEATH KARMAS"},
            {"id": 45,  "text": "GO TO CO-OPERATIVE BANK FOR SETTLEMENT OF LOAN"},
            {"id": 47,  "text": "MOTHER HOSPITALISED"},
            {"id": 48,  "text": "MARRIAGE REGISTRATION (TO GET CERTIFICATE)"},
            {"id": 50,  "text": "HAND BROKEN DUE TO ACCIDENT"},
            {"id": 53,  "text": "RTO OFFICE WORK"},
            {"id": 54,  "text": "GO TO CO-OP BANK - ACCOUNT OPENING FOR LOAN"},
            {"id": 55,  "text": "TO GO TO EMPLOYMENT EXCHANGE FOR DEGREE REGISTRATION"},
            {"id": 56,  "text": "ROOM SHIFTING"},
            {"id": 57,  "text": "VILLAGE OFFICE HOUSE PROBLEM"},
            {"id": 58,  "text": "PTA MEETING"},
            {"id": 59,  "text": "FESTIVAL RAKHI DAY"},
            {"id": 60,  "text": "RAKSHABANDHAN"},
            {"id": 62,  "text": "BRANCH IS NOT OPENED ON THOSE DAYS"},
            {"id": 63,  "text": "PREMARRIAGE FUNCTION"},
            {"id": 64,  "text": "POOJA AT HOME"},
            {"id": 65,  "text": "AVANIAVITTAM (RELIGIOUS FESTIVAL)"},
            {"id": 67,  "text": "GO TO COURT"},
            {"id": 69,  "text": "UNCLE HOSPITALISED"},
            {"id": 70,  "text": "FAMILY FUNCTION - AVANIAVITTAM"},
            {"id": 71,  "text": "FESTIVAL"},
            {"id": 72,  "text": "CHILD HOSPITALISED FEVER"},
            {"id": 73,  "text": "ADMISSION FOR MY DAUGHTER"},
            {"id": 74,  "text": "GO TO COIMBATORE TO ATTEND FAMILY FUNCTION"},
            {"id": 75,  "text": "GOING TO HOSPITAL ALONG WITH GRANDMOTHER"},
            {"id": 76,  "text": "ACCOMPANYING GRANDMOTHER (SICK) TO HOSPITAL"},
            {"id": 77,  "text": "GO TO UNIVERSITY TO FILL SECOND YEAR APPLICATION (MBA COURSE)"},
            {"id": 78,  "text": "ONAM"},
            {"id": 79,  "text": "COUNSELLING OF MY SON FOR ENGINEERING AT KOLLAM"},
            {"id": 80,  "text": "GO TO PANCHAYATH FOR MARRIAGE REGISTRATION"},
            {"id": 81,  "text": "GO TO HUSBAND'S HOME AT KOTTAYAM"},
            {"id": 84,  "text": "MOTHER'S OPERATION"},
            {"id": 85,  "text": "CORRECTION OF MY FAMILY CARD (RATION CARD)"},
            {"id": 86,  "text": "FAMILY PROBLEM"},
            {"id": 87,  "text": "DAUGHTER HAS TO BE HOSPITALISED FOR CHECK UP"},
            {"id": 90,  "text": "COLLEGE CONVOCATION"},
            {"id": 91,  "text": "WENT TO AIRPORT"},
            {"id": 93,  "text": "GO TO GOVERNMENT OFFICE"},
            {"id": 95,  "text": "GO TO BANK"},
            {"id": 96,  "text": "SANJAYANAM GRANDFATHER DEATH"},
            {"id": 99,  "text": "TAMIL NADU ASSEMBLY ELECTION"},
            {"id": 100, "text": "TO CONSULT DOCTOR AT ECHS THRISSUR"},
            {"id": 101, "text": "DISPOSAL OF FAMILY PROPERTY"},
            {"id": 102, "text": "BETROTHAL OF OWN SISTER"},
            {"id": 103, "text": "ATTEND THE M.P. ELECTION"},
            {"id": 104, "text": "DAUGHTER'S FIRST BIRTHDAY"},
            {"id": 107, "text": "PERSONAL PROBLEMS"},
            {"id": 109, "text": "TO ATTEND THE MARRIAGE FUNCTION AT KANNUR"},
            {"id": 112, "text": "LOCAL VEHICLE STRIKE"},
            {"id": 113, "text": "TO ACCOMPANY MY SISTER TO HOSPITAL FOR MONTHLY CHECK UP"},
            {"id": 114, "text": "BROTHERS ENGAGEMENT"},
            {"id": 115, "text": "GO TO PALANI TEMPLE"},
            {"id": 116, "text": "MARRIAGE OF NIECE"},
            {"id": 117, "text": "GO TO POLICE STATION"},
            {"id": 118, "text": "11TH DAY OF DEATH OF BROTHER IN LAW"},
            {"id": 119, "text": "TO COLLECT M.COM MARK LIST"},
            {"id": 120, "text": "RENEWAL AND CORRECTION ON RATION CARD"},
            {"id": 122, "text": "BLOOD TEST AND SCAN AS PER DOCTORS INSTRUCTION"},
            {"id": 123, "text": "FRIEND'S MARRIAGE"},
            {"id": 124, "text": "TO ATTEND COUNSELLING EDCET"},
            {"id": 125, "text": "MEDICAL CHECK UP OF DAUGHTER"},
            {"id": 127, "text": "GOING FOR DRIVING LICENCE TEST"},
            {"id": 129, "text": "GO TO EXAMINATION"},
            {"id": 130, "text": "TO REMIT FEES FOR REGISTER M.COM CORRESPONDENCE COURSE"},
            {"id": 131, "text": "FEVER WITH BODY PAIN"},
            {"id": 132, "text": "OWN ENGAGEMENT"},
            {"id": 133, "text": "CHILDREN'S FEVER"},
            {"id": 134, "text": "FAMILY FUNCTION TOWARDS SISTER PREGNANCY"},
            {"id": 135, "text": "MEDICAL CHECK UP TO WIFE"},
            {"id": 136, "text": "ENGAGEMENT OF NIECE"},
            {"id": 138, "text": "BUS STRIKE"},
            {"id": 139, "text": "SISTER'S BETROTHAL"},
            {"id": 140, "text": "MARRIAGE PROPOSAL"},
            {"id": 141, "text": "WHEEZING"},
            {"id": 142, "text": "NEPHEW MARRIAGE"},
            {"id": 143, "text": "ATTEND MBA SEMINAR CLASS"},
            {"id": 144, "text": "RATION CARD CORRECTION & DOCUMENT REGISTRATION"},
            {"id": 145, "text": "GO TO NATIVE FOR ATTENDING ONAM FESTIVAL"},
            {"id": 146, "text": "GRANDMOTHER'S SANJAYANAM"},
            {"id": 147, "text": "ENGAGEMENT"},
            {"id": 149, "text": "FATHER'S DEATH ANNIVERSARY"},
            {"id": 150, "text": "OPERATION OF CHILD IN URINARY SYSTEM"},
            {"id": 151, "text": "MOTHER HOSPITAL CHECK UP"},
            {"id": 158, "text": "MA EXAMS"},
            {"id": 160, "text": "HUSBAND GOING ABROAD"},
            {"id": 161, "text": "SANCHAYANAM: SISTERS DEATH"},
            {"id": 162, "text": "WANT TO GO HOSPITAL"},
            {"id": 163, "text": "VIVA VOCE EXAM"},
            {"id": 164, "text": "LATE PUNCHING"},
            {"id": 166, "text": "DAUGHTER ADMISSION AT WAYANAD"},
            {"id": 170, "text": "SETTLEMENT OF DCRG CLAIM"},
            {"id": 172, "text": "ACCOMPANIED MOTHER-IN-LAW TO ADMIT IN HOSPITAL"},
            {"id": 175, "text": "EMPLOYMENT OFFICE"},
            {"id": 176, "text": "DEGREE CERTIFICATE TAKEN"},
            {"id": 177, "text": "PROPERTY REGISTRATION AGREEMENT AT COIMBATORE"},
            {"id": 178, "text": "MOTHER'S MEDICAL CHECK UP"},
            {"id": 180, "text": "PROPERTY REGISTRATION AT CHENNAI"},
            {"id": 181, "text": "SANJAYANAM: AUNT'S DEATH"},
            {"id": 182, "text": "GO TO AIRPORT"},
            {"id": 183, "text": "BAPTISM OF SISTER'S CHILD"},
            {"id": 187, "text": "RAMZAN"},
            {"id": 188, "text": "SISTER IN LAW'S MARRIAGE"},
            {"id": 189, "text": "TO GO TO COIMBATORE, HUSBAND'S NATIVE DUE TO DEEPAVALI"},
            {"id": 190, "text": "TO TAKE GAS CONNECTION"},
            {"id": 191, "text": "TO MEET NOTARY OFFICER"},
            {"id": 192, "text": "TO RECEIVE A MARK SHEET"},
            {"id": 193, "text": "TAKE WIFE TO HOSPITAL FOR DELIVERY"},
            {"id": 194, "text": "UNCLE HOSPITALISED FOR SURGERY"},
            {"id": 196, "text": "TO GO TO UNIVERSITY AND BANK"},
            {"id": 197, "text": "MEDICAL CHECK UP TO MY WIFE"},
            {"id": 198, "text": "EID-UL-FITHAR (RAMZAN)"},
            {"id": 202, "text": "RAMZAN"},
            {"id": 203, "text": "MOTHER HOSPITALISED"},
            {"id": 204, "text": "MEDICAL CHECK UP TO WIFE"},
            {"id": 205, "text": "GO TO PASSPORT OFFICE"},
            {"id": 206, "text": "SISTER'S ENGAGEMENT"},
            {"id": 207, "text": "UNCLE HOSPITALISED"},
            {"id": 209, "text": "MOTHER NOT WELL"},
            {"id": 210, "text": "GO TO THIRUPATHI"},
            {"id": 211, "text": "GO TO THIRUPATHI TEMPLE"},
            {"id": 213, "text": "DEATH ANNIVERSARY OF GRANDMOTHER"},
            {"id": 214, "text": "MARRIAGE OF COUSIN"},
            {"id": 217, "text": "FRIENDS ENGAGEMENT"},
            {"id": 218, "text": "PERSONAL"},
            {"id": 219, "text": "EYE OPERATION"},
            {"id": 220, "text": "THROAT PAIN"},
            {"id": 221, "text": "EID FESTIVAL"},
            {"id": 222, "text": "AFTER DEATH POOJA OF GRANDFATHER"},
            {"id": 224, "text": "BROTHER'S MEDICAL TREATMENT"},
            {"id": 226, "text": "INTERVIEW AT BANGALORE"},
            {"id": 229, "text": "ALLERGY (SKIN DISEASE)"},
            {"id": 231, "text": "MEDICAL CHECK UP"},
            {"id": 232, "text": "DOMESTIC AFFAIRS GOING TO HYDERABAD TO ESCORT DAUGHTER FOR EXAM"},
            {"id": 233, "text": "GO TO HOSPITAL FOR TAKING X-RAY"},
            {"id": 234, "text": "SISTERS HOUSE WARMING"},
            {"id": 235, "text": "GOING TO UNIVERSITY"},
            {"id": 236, "text": "GO TO EMPLOYMENT OFFICE FOR RENEWAL OF EMPLOYMENT CARD"},
            {"id": 238, "text": "GO TO COLLEGE FOR RECEIVING CERTIFICATE"},
            {"id": 239, "text": "GOING TO UNIVERSITY CONVOCATION FUNCTION"},
            {"id": 242, "text": "RAMZAN"},
            {"id": 243, "text": "DEEPAVALI FESTIVAL - GO TO HOME"},
            {"id": 244, "text": "GOING TO COLLEGE REGARDING BROTHER MBA ADMISSION"},
            {"id": 245, "text": "HOUSE WARMING"},
            {"id": 246, "text": "ACCOMPANYING DAUGHTER TO NAVODAYA SCHOOL"},
            {"id": 247, "text": "LASIK EYE OPERATION"},
            {"id": 251, "text": "GO TO HOME (URGENT CALL FROM HOME)"},
            {"id": 254, "text": "OWN BROTHER EXPIRED"},
            {"id": 255, "text": "HOUSE WARMING"},
            {"id": 256, "text": "TO GO TO THE HOSPITAL"},
            {"id": 259, "text": "PREGNANT WITH EDD"},
            {"id": 261, "text": "LEARNING TEST OF VEHICLE"},
            {"id": 264, "text": "MEDICAL CHECKUP OF MOTHER"},
            {"id": 265, "text": "16TH DAY OF DEATH CEREMONY OF BROTHER"},
            {"id": 266, "text": "FOR TAKING VOTER'S ID"},
            {"id": 270, "text": "GO TO HOME FOR DIWALI FESTIVAL"},
            {"id": 271, "text": "HUSBAND HOSPITALISED BY ACCIDENT"},
            {"id": 272, "text": "NAME CEREMONY OF SON"},
            {"id": 274, "text": "DEATH ANNIVERSARY OF FATHER IN LAW"},
            {"id": 275, "text": "SISTER HOSPITALISED"},
            {"id": 276, "text": "BROTHER IN LAW'S MARRIAGE"},
            {"id": 277, "text": "GO TO PASSPORT OFFICE"},
            {"id": 278, "text": "HARTHAL (NO TRANSPORTATION)"},
            {"id": 279, "text": "HARTHAL"},
            {"id": 280, "text": "HARTHAL AT KODUNGALLUR"},
            {"id": 281, "text": "SANJAYANAM OF FATHER"},
            {"id": 283, "text": "TRANSFER FROM ONE BRANCH TO ANOTHER"},
            {"id": 284, "text": "OWN FEVER & CHILD'S ILLNESS"},
            {"id": 285, "text": "CHURCH FESTIVAL"},
            {"id": 286, "text": "SURGERY OF HUSBAND"},
            {"id": 287, "text": "REGISTRATION OF CAR"},
            {"id": 288, "text": "FEVER (CHIKUNGUNYA)"},
            {"id": 290, "text": "DUE TO DENTAL PAIN"},
            {"id": 291, "text": "RELATIVE EXPIRED"},
            {"id": 292, "text": "TO ATTEND THE RELATIVES MARRIAGE FUNCTION"},
            {"id": 293, "text": "MOTHER'S SISTER EXPIRED"},
            {"id": 295, "text": "TAKING BIRTH CERTIFICATE OF SON & ADMISSION TO SCHOOL"},
            {"id": 296, "text": "FEVER & CHEST PAIN"},
            {"id": 299, "text": "SANJAYANAM OF MOTHER'S SISTER"},
            {"id": 300, "text": "GRANDFATHER DEATH AFTER KARMA"},
            {"id": 301, "text": "DOCTOR'S CONSULTATION OF MY SPOUSE"},
            {"id": 302, "text": "SUICIDE ATTEMPT OF SISTER-IN-LAW"},
            {"id": 303, "text": "5TH DAY OF DEATH CEREMONY OF MY FATHER"},
            {"id": 304, "text": "GO TO UNIVERSITY FOR DEGREE CERTIFICATE"},
            {"id": 305, "text": "RED EYE"},
            {"id": 306, "text": "NAMING CEREMONY OF SISTER'S DAUGHTER"},
            {"id": 307, "text": "KETTUNIRA AT HOME"},
            {"id": 309, "text": "TO ATTEND THE DANCE COMPETITION OF DAUGHTER"},
            {"id": 310, "text": "PRE MARRIAGE COUNSELLING"},
            {"id": 311, "text": "MOTHER MEETING IN CHILDREN'S SCHOOL"},
            {"id": 312, "text": "CONSULT DOCTOR (CHEST PAIN & BREATHING PROBLEM)"},
            {"id": 315, "text": "GO TO HOME FOR CHURCH FESTIVAL & EYE CHECK UP"},
            {"id": 316, "text": "MOTHER-IN-LAW HOSPITALISED"},
            {"id": 317, "text": "KETTUM NIRA AT HOME"},
            {"id": 318, "text": "NO TRANSPORTATION"},
            {"id": 319, "text": "TO ATTEND MBA CLASSES"},
            {"id": 321, "text": "MOTHER HEALTH PROBLEM"},
            {"id": 322, "text": "GOING TO TEMPLE (SABARIMALA)"},
            {"id": 323, "text": "GO TO SABARIMALA"},
            {"id": 324, "text": "MBA PRESENTATION"},
            {"id": 325, "text": "MARRIAGE OF COUSIN BROTHER"},
            {"id": 326, "text": "MATERNITY LEAVE (DELIVERY)"},
            {"id": 327, "text": "GRANDMOTHER'S 16TH DAY OF DEMISE"},
            {"id": 328, "text": "BROTHER HOSPITALISED BY ACCIDENT"},
            {"id": 329, "text": "SABARIMALA PILGRIMAGE"},
            {"id": 330, "text": "PURCHASE OF GOLD FOR MY ENGAGEMENT"},
            {"id": 331, "text": "PILGRIMAGE TO SABARIMALA"},
            {"id": 332, "text": "HAD BEEN TO AIRPORT TO SEND OFF HUSBAND"},
            {"id": 333, "text": "GO TO DRIVING LICENCE"},
            {"id": 334, "text": "DEATH ANNIVERSARY FUNCTION AT HOME"},
            {"id": 336, "text": "TO CONSULT DOCTOR (NECK SPRAIN)"},
            {"id": 338, "text": "GO TO SABARIMALA"},
            {"id": 339, "text": "TO ATTEND PROGRAMME AT ICSI CHENNAI"},
            {"id": 340, "text": "FATHER-IN-LAW'S ECHO TEST, ANGIOGRAM"},
            {"id": 341, "text": "UNCLE'S ENGAGEMENT"},
            {"id": 342, "text": "TO ATTEND GET TOGETHER FUNCTION AT COLLEGE"},
            {"id": 344, "text": "PILGRIMAGE TO THIRUPATHI (ANNAPRASAM OF NEPHEW)"},
            {"id": 345, "text": "ALLERGY"},
            {"id": 346, "text": "FATHER'S CEREMONY"},
            {"id": 350, "text": "PILGRIMAGE TO PAZHANI"},
            {"id": 351, "text": "TO GO TO SCHOOL FOR ATTENDING PTA MEETING"},
            {"id": 352, "text": "MBA SEMESTER EXAM"},
            {"id": 353, "text": "GO TO HOSPITAL"},
            {"id": 354, "text": "FATHER-IN-LAW'S ECHO TEST, ANGIOGRAM"},
            {"id": 355, "text": "MARRIAGE REGISTRATION CONFIRMATION"},
            {"id": 356, "text": "GO TO HOME (BAKRID)"},
            {"id": 357, "text": "GRANDMOTHER HOSPITALISED (SERIOUS)"},
            {"id": 358, "text": "GO TO CHILDREN'S SCHOOL FOR SIGNING PROGRESS REPORT"},
            {"id": 359, "text": "TO SEE OFF SON AND FAMILY GOING TO MUMBAI"},
            {"id": 360, "text": "LAND SURVEYING"},
            {"id": 361, "text": "BAKRID"},
            {"id": 362, "text": "COLLECTION OF FAMILY RATION CARD"},
            {"id": 363, "text": "FATHER IN LAW'S DEATH ANNIVERSARY"},
            {"id": 368, "text": "URGENT CALL FROM HOME"},
            {"id": 369, "text": "GO TO HOSPITAL - EYE PAIN"},
            {"id": 370, "text": "BODY PAIN AND FEVER"},
            {"id": 371, "text": "BROTHERS MARRIAGE"},
            {"id": 374, "text": "SURGERY AND BED REST"},
            {"id": 375, "text": "CHILD HOSPITALIZED FOR EYE OPERATION"},
            {"id": 376, "text": "FAMILY FUNCTION AT KANNUR"},
            {"id": 385, "text": "CHAKKULATHUKAVU PONKALA"},
            {"id": 386, "text": "RAMZAN"},
            {"id": 387, "text": "FAMILY PROBLEMS"},
            {"id": 388, "text": "HUSBAND GOING TO SABARIMALA"},
            {"id": 389, "text": "ATTEND FUNCTION"},
            {"id": 392, "text": "DELIVERY"},
            {"id": 393, "text": "CHILD'S ILLNESS"},
            {"id": 394, "text": "ELDER BROTHER MARRIAGE"},
            {"id": 395, "text": "FATHER'S MEDICAL CHECK UP"},
            {"id": 396, "text": "SABARIMALA PILGRIMAGE OF HUSBAND AND SON"},
            {"id": 397, "text": "GOING TO BANK"},
            {"id": 398, "text": "TO MEET FRIEND"},
            {"id": 399, "text": "GO TO HOSPITAL"},
            {"id": 400, "text": "DUE TO MOTHER'S ILLNESS"},
            {"id": 402, "text": "TO CONSULT DOCTOR FOR DAUGHTER"},
            {"id": 403, "text": "UNIVERSITY REGISTRATION FOR SISTER"},
            {"id": 404, "text": "SABARIMALA PILGRIMAGE OF HUSBAND AND SON"},
            {"id": 405, "text": "FATHER'S MEDICAL CHECK UP"},
            {"id": 406, "text": "TO ATTEND MOTHER'S POST DEMISE RITUALS"},
            {"id": 408, "text": "HUSBAND GOING TO SABARIMALA"},
            {"id": 410, "text": "GO TO SABARIMALA ON FOOT"},
            {"id": 411, "text": "5TH DAY OF GRANDMOTHER'S DEATH"},
            {"id": 412, "text": "TO COLLECT TRANSFER CERTIFICATE"},
            {"id": 413, "text": "GO TO SABARIMALA"},
            {"id": 414, "text": "ANNUAL FUNCTION IN FAMILY TEMPLE"},
            {"id": 415, "text": "BROTHER HOSPITALISED"},
            {"id": 416, "text": "FATHER'S OPERATION"},
            {"id": 417, "text": "MARRIAGE PURPOSE"},
            {"id": 418, "text": "OWN MARRIAGE PURPOSE"},
            {"id": 419, "text": "MARRIAGE PURPOSE"},
            {"id": 420, "text": "CERTIFICATE ATTESTATION"},
            {"id": 421, "text": "ONGOING CONSTRUCTION OF NEW HOUSE"},
            {"id": 422, "text": "WENT TO TEMPLE WITH FAMILY"},
            {"id": 423, "text": "TO CONSULTING DOCTOR DOING COLONOSCOPY"},
            {"id": 424, "text": "TO CONSULT DOCTOR FOR FATHER"},
            {"id": 425, "text": "TO ATTEND COURT FOR DIVORCE CASE"},
            {"id": 426, "text": "FATHER HOSPITAL CHECK UP"},
            {"id": 427, "text": "MOTHER'S SICK - HOSPITALISED"},
            {"id": 428, "text": "NO REASON"},
            {"id": 429, "text": "GO TO GURUVAYUR TEMPLE"},
            {"id": 431, "text": "PONGAL FESTIVAL"},
            {"id": 432, "text": "PONGAL FESTIVAL"},
            {"id": 433, "text": "GRANDMOTHER EXPIRED"},
            {"id": 434, "text": "TO ATTEND MA CLASS"},
            {"id": 435, "text": "TYPHOID"},
            {"id": 436, "text": "HOSTEL CLOSED FOR CHRISTMAS VACATION"},
            {"id": 437, "text": "CHRISTMAS FAMILY GET-TOGETHER"},
            {"id": 438, "text": "SANJAYANAM"},
            {"id": 440, "text": "FATHER GOING ABROAD"},
            {"id": 441, "text": "TO ATTEND COURT"},
            {"id": 442, "text": "PAPER PRESENTATION"},
            {"id": 443, "text": "CONSULT DOCTOR DUE TO BACK PAIN"},
            {"id": 444, "text": "HOSPITALIZED"},
            {"id": 445, "text": "FATHER'S MEDICAL CHECK UP AT COIMBATORE"},
            {"id": 446, "text": "TO ATTEND NEW YEAR RELIGIOUS SERVICE"},
            {"id": 447, "text": "HOUSE REPAIR"},
            {"id": 448, "text": "HOSPITALIZED"},
            {"id": 449, "text": "TO GO TO NAVAGRAHA TEMPLES AT TAMIL NADU"},
            {"id": 450, "text": "HUSBAND HOSPITALIZED"},
            {"id": 451, "text": "16TH DAY OF GRANDMOTHER'S DEATH"},
            {"id": 452, "text": "M.COM EXAMINATION"},
            {"id": 455, "text": "LATE COMING"},
            {"id": 456, "text": "DEATH ANNIVERSARY OF FATHER (SRADHAM)"},
            {"id": 457, "text": "MALAYAATOOR PILGRIMAGE"},
            {"id": 460, "text": "MBA EXAMINATION"},
            {"id": 461, "text": "SANJAYANAM OF FATHER IN LAW"},
            {"id": 462, "text": "GOLD AND DRESS PURCHASE IN CONNECTION WITH MARRIAGE"},
            {"id": 463, "text": "RELIGIOUS FUNCTION"},
            {"id": 464, "text": "MARRIAGE REGISTRATION"},
            {"id": 465, "text": "GO TO SABARIMALA"},
            {"id": 466, "text": "ACCIDENT TO MY BROTHER"},
            {"id": 467, "text": "GO TO HOME IN CONNECTION WITH MARRIAGE PURPOSE"},
            {"id": 468, "text": "PONGAL FESTIVAL"},
            {"id": 470, "text": "IMPORTANT PERSONAL WORK AT KOLLAM"},
            {"id": 471, "text": "FOR COLLECTING HALL TICKET FOR PG EXAMINATION"},
            {"id": 472, "text": "PONGAL FESTIVAL"},
            {"id": 473, "text": "AUTO STRIKE"},
            {"id": 474, "text": "HARTHAL"},
            {"id": 475, "text": "FEAST IN CHURCH"},
            {"id": 476, "text": "ADIYANTHIRAM OF FATHER IN LAW"},
            {"id": 478, "text": "40TH DAY OF MY GRANDMOTHER'S DEATH"},
            {"id": 481, "text": "GO TO CHURCH FOR NEW YEAR"},
            {"id": 482, "text": "TAKING BROTHER TO MEDICAL COLLEGE HOSPITAL FOR CT SCAN"},
            {"id": 483, "text": "STRIKE"},
            {"id": 484, "text": "UNABLE TO REACH DUE TO HARTHAL"},
            {"id": 485, "text": "FATHER-IN-LAW HOSPITALISED"},
            {"id": 486, "text": "MOTHER IN LAW NOT WELL"},
            {"id": 487, "text": "FATHER GOING TO SABARIMALA"},
            {"id": 488, "text": "NO TRANSPORTATION"},
            {"id": 489, "text": "SON COMING FROM ABROAD"},
            {"id": 490, "text": "NO TRANSPORTATION DUE TO STATE WIDE HARTHAL"},
            {"id": 491, "text": "SON'S ENGAGEMENT FUNCTION"},
            {"id": 492, "text": "FAMILY TOUR"},
            {"id": 494, "text": "LOCAL FESTIVAL"},
            {"id": 495, "text": "FOR RECEIVE PASSPORT"},
            {"id": 496, "text": "OWN BETROTHAL"},
            {"id": 497, "text": "VOTER ID REGISTRATION"},
            {"id": 498, "text": "PONGAL FESTIVAL"},
            {"id": 499, "text": "URGENT PERSONAL WORK"},
            {"id": 501, "text": "SWARNA PRASHNAM AT FAMILY TEMPLE"},
            {"id": 504, "text": "GO TO CHURCH"},
            {"id": 505, "text": "GO TO VELANKANNY MASS"},
            {"id": 506, "text": "TO GO TO CHILD'S SCHOOL"},
            {"id": 507, "text": "VEHICLE LOAN SETTLEMENT"},
            {"id": 508, "text": "TAKING AYURVEDIC TREATMENT FOR ARTHRITIS"},
            {"id": 509, "text": "TO ATTEND THE FOUR WHEELER DRIVING LICENCE TEST"},
            {"id": 510, "text": "NAMING CEREMONY OF BROTHER'S CHILD"},
            {"id": 511, "text": "TO PURCHASE GOLD IN CONNECTION WITH MY MARRIAGE"},
            {"id": 512, "text": "HOUSEWARMING"},
            {"id": 514, "text": "NIECE'S MARRIAGE"},
            {"id": 517, "text": "GOING TO PASSPORT OFFICE"},
            {"id": 518, "text": "SON'S MARRIAGE"},
            {"id": 521, "text": "SANCHYANAM OF COUSIN BROTHER"},
            {"id": 522, "text": "TO INVITE FRIENDS, RELATIVES AND SENIORS FOR MARRIAGE"},
            {"id": 524, "text": "FOR GETTING AWARD FROM NATIONAL INTEGRITY CULTURAL ACADEMY"},
            {"id": 525, "text": "TO COLLECT VOTER'S IDENTITY CARD"},
            {"id": 526, "text": "TO REMIT EXAMINATION FEE FOR MBA"},
            {"id": 529, "text": "SANCHAYANAM OF FATHER'S BROTHER"},
            {"id": 530, "text": "ADIYANTHIRAM OF SISTER'S FATHER-IN-LAW"},
            {"id": 531, "text": "ALUMNI MEET"},
            {"id": 533, "text": "MEDICAL CHECK UP"},
            {"id": 534, "text": "TO ATTEND TO SOME URGENT DOMESTIC MATTERS"},
            {"id": 536, "text": "FESTIVAL, ALL MY FAMILY MEMBERS COMPULSORY ATTEND THIS"},
            {"id": 538, "text": "ACCOMPANYING GRANDMOTHER TO HOSPITAL"},
            {"id": 540, "text": "INVITING GUESTS FOR SISTER'S MARRIAGE"},
            {"id": 541, "text": "MEDICAL REVIEW AT AIMS COCHIN"},
            {"id": 542, "text": "CRITICAL CONDITION, NEED MORE CARE"},
            {"id": 544, "text": "POOJA"},
            {"id": 545, "text": "HARTAL - TRAVELLING DAILY TO REACH OFFICE"},
            {"id": 547, "text": "COLLECT IDENTITY CARD"},
            {"id": 548, "text": "GO TO CHURCH"},
            {"id": 550, "text": "ACCOMPANY FATHER TO AMRITA HOSPITAL, ERNAKULAM"},
            {"id": 551, "text": "NAMING CEREMONY OF SISTERS DAUGHTER"},
            {"id": 552, "text": "TO ATTEND COURT CASE"},
            {"id": 553, "text": "GO TO COLLEGE (SUBMIT EXAM FORM)"},
            {"id": 554, "text": "SISTERS MEDICAL CHECK UP"},
            {"id": 555, "text": "MATERNITY"},
            {"id": 559, "text": "OWN BLOOD TEST & USG"},
            {"id": 560, "text": "PONGAL FESTIVAL"},
            {"id": 563, "text": "FOR PONGAL FESTIVAL"},
            {"id": 564, "text": "MEDICAL CHECK UP FOR MY DAUGHTER"},
            {"id": 565, "text": "TO COLLECT MY NEW FAMILY RATION CARD FROM TALUK OFFICE"},
            {"id": 566, "text": "GO TO THE HOSPITAL"},
            {"id": 567, "text": "HOUSE OPENING FUNCTION"},
            {"id": 568, "text": "SCHOOL ADMISSION FOR MY DAUGHTER"},
            {"id": 569, "text": "GO TO PAZHANI MALA TEMPLE"},
            {"id": 570, "text": "MEDICAL CHECKUP AT AMRITHA HOSPITAL"},
            {"id": 572, "text": "GO TO SISTER'S HOME MYSORE"},
            {"id": 573, "text": "OWN SACRED BANGLE DAY (VALAIKAPPU)"},
            {"id": 574, "text": "MY SISTER MARRIAGE"},
            {"id": 575, "text": "NAME CEREMONY OF DAUGHTER"},
            {"id": 576, "text": "STOMACH PAIN"},
            {"id": 577, "text": "BROTHER'S HOUSE WARMING"},
            {"id": 578, "text": "TO ATTEND THE SCHOOL ANNIVERSARY FUNCTION OF DAUGHTER"},
            {"id": 579, "text": "MY SON BIRTHDAY"},
            {"id": 580, "text": "GO TO HOSPITAL"},
            {"id": 581, "text": "FATHER-IN-LAW HOSPITALISED"},
            {"id": 582, "text": "FAMILY FUNCTION"},
            {"id": 583, "text": "RITUAL FUNCTION"},
            {"id": 584, "text": "VIRAL FEVER AND COUGH"},
            {"id": 587, "text": "TO COLLECT TC FROM COLLEGE"},
            {"id": 588, "text": "NIECE'S MARRIAGE"},
            {"id": 589, "text": "TO ATTEND TO LAND REVENUE WORK AT NATIVE PLACE"},
            {"id": 592, "text": "BROTHER EXPIRED"},
            {"id": 594, "text": "NAMING CEREMONY OF SISTER'S SON"},
            {"id": 595, "text": "PERSONAL WORK AT TRIVANDRUM"},
            {"id": 597, "text": "TRAFFIC BLOCK"},
            {"id": 598, "text": "GOING TO NATIVE PLACE"},
            {"id": 599, "text": "CONSULT TO DOCTOR (EYE SPECIALIST)"},
            {"id": 600, "text": "RELATIVE DEATH"},
            {"id": 601, "text": "MY HOUSE OPENING FUNCTION"},
            {"id": 603, "text": "5TH DAY OF GRAND MOTHER EXPIRED"},
            {"id": 604, "text": "SWARNA PRASHNAM AT FAMILY TEMPLE"},
            {"id": 605, "text": "SISTER-IN-LAW SERIOUSLY HOSPITALISED"},
            {"id": 607, "text": "11TH DAY OF UNCLE'S DEATH"},
            {"id": 608, "text": "DEATH ANNIVERSARY OF MOTHER IN LAW"},
            {"id": 609, "text": "COUSIN'S ENGAGEMENT"},
            {"id": 610, "text": "SISTER'S ENGAGEMENT"},
            {"id": 611, "text": "BROTHER MARRIAGE"},
            {"id": 612, "text": "COUSIN'S MARRIAGE"},
            {"id": 613, "text": "ACCOMPANY DAUGHTER FOR ENGINEERING ENTRANCE"},
            {"id": 614, "text": "GO TO MRO OFFICE FOR FAMILY CERTIFICATE APPLY"},
            {"id": 616, "text": "DEATH ANNIVERSARY OF GRANDMOTHER"},
            {"id": 617, "text": "HIGH FEVER"},
            {"id": 618, "text": "DEATH ANNIVERSARY GRANDFATHER"},
            {"id": 619, "text": "MEDICAL CHECKUP FOR MY SON"},
            {"id": 621, "text": "MARRIAGE IN THE FAMILY"},
            {"id": 622, "text": "TO COLLECT VOTERS ID CARD"},
            {"id": 624, "text": "APPLYING DRIVING LICENSE AND GOING TO MADURAI FOR PG DEGREE REGISTRATION"},
            {"id": 625, "text": "OWN TMT TEST AT CALICUT MEDICAL COLLEGE"},
            {"id": 626, "text": "BACK PAIN & VOMITTING"},
            {"id": 627, "text": "COUSIN'S ENGAGEMENT"},
            {"id": 628, "text": "FATHER'S DEATH ANNIVERSARY"},
            {"id": 629, "text": "FOR CONDUCT AN EXAM"},
            {"id": 630, "text": "GO TO SUB-REGISTRAR OFFICE"},
            {"id": 631, "text": "URGENT NEED TO GO TO UNIVERSITY"},
            {"id": 632, "text": "LEFT FROM OFFICE FOR FATHER'S ILLNESS"},
            {"id": 633, "text": "FATHER HOSPITALISED"},
            {"id": 634, "text": "LEFT FROM OFFICE TO ARRANGE CASH FOR FATHER'S HEART OPERATION"},
            {"id": 636, "text": "FATHER'S HEART OPERATION"},
            {"id": 637, "text": "PILGRIMAGE TO VELANKANNI"},
            {"id": 639, "text": "BROTHER-IN-LAW MARRIAGE"},
            {"id": 640, "text": "MEDICAL CHECK UP FOR MY SON"},
            {"id": 641, "text": "GO TO TRIVANDRUM - FAMILY FUNCTION CONNECTED WITH ATTUKAL PONGALA"},
            {"id": 643, "text": "GOING TO HOSPITAL"},
            {"id": 644, "text": "DYSENTERY & FEVER"},
            {"id": 645, "text": "GO TO URGENT REQUIREMENT"},
            {"id": 648, "text": "TAKE MOTHER TO HOSPITAL"},
            {"id": 649, "text": "BANK PURPOSE"},
            {"id": 650, "text": "WIFE'S ILLNESS"},
            {"id": 652, "text": "GO TO CHAVAKKAD THALUK OFFICE"},
            {"id": 653, "text": "UNIVERSITY EXAMINATION"},
            {"id": 654, "text": "GO TO NATIVE FOR TEMPLE"},
            {"id": 655, "text": "GO TO DRIVING TEST"},
            {"id": 656, "text": "GO TO COLLEGE (FOR EXAM ADMIT CARD)"},
            {"id": 657, "text": "MAHA SHIVARATRI FESTIVAL"},
            {"id": 658, "text": "GO TO NAVODAYA SCHOOL FOR SIGNING PROGRESS REPORT OF MY DAUGHTER"},
            {"id": 659, "text": "MEDICAL CHECKUP OF MY SON"},
            {"id": 661, "text": "LOCAL FESTIVAL"},
            {"id": 662, "text": "FEVER AND BACK PAIN"},
            {"id": 663, "text": "MATERNITY LEAVE"},
            {"id": 664, "text": "FATHER'S DEATH ANNIVERSARY"},
            {"id": 665, "text": "FEVER, VOMITTING, HEADACHE"},
            {"id": 666, "text": "OPERATION OF HUSBAND"},
            {"id": 667, "text": "GO TO KOTTAYAM, OWN HOUSE"},
            {"id": 668, "text": "GO TO PANCHAYATH FOR RENEWAL OF ID CARD"},
            {"id": 669, "text": "MOTHER ILLNESS"},
            {"id": 670, "text": "GO TO FAMILY TEMPLE (FESTIVAL)"},
            {"id": 671, "text": "FAMILY FUNCTION"},
            {"id": 672, "text": "DAUGHTER MONTHLY CHECKUP TO CHETTINAD HOSPITAL"},
            {"id": 673, "text": "POOJA AT TEMPLE"},
            {"id": 674, "text": "GO TO ESI OFFICE"},
            {"id": 675, "text": "41ST DAY OF FATHER-IN-LAW DEATH"},
            {"id": 676, "text": "GOING TO HOSPITAL"},
            {"id": 677, "text": "BANK PURPOSE, HOUSE WARMING"},
            {"id": 679, "text": "BIRTHDAY FUNCTION IN MY HOME"},
            {"id": 680, "text": "TO RECEIVE BROTHER FROM KERALA"},
            {"id": 682, "text": "GO TO HOSPITAL"},
            {"id": 683, "text": "28TH DAY OF CHILD"},
            {"id": 684, "text": "MACHAD MAMANGAM"},
            {"id": 685, "text": "APPLYING DRIVING LICENSE"},
            {"id": 686, "text": "GO TO EMPLOYMENT OFFICE FOR PG DEGREE REGISTRATION"},
            {"id": 687, "text": "FAMILY FUNCTION"},
            {"id": 688, "text": "FAMILY FUNCTION GO TO HOME"},
            {"id": 689, "text": "CHILD SICK (HAND BURNED)"},
            {"id": 690, "text": "HOLI FESTIVAL"},
            {"id": 691, "text": "GO TO MUNICIPAL OFFICE FOR MARRIAGE REGISTRATION"},
            {"id": 692, "text": "PERINGOTTUKARA UTSAVAM"},
            {"id": 693, "text": "TO ATTEND TO CERTAIN URGENT MATTERS AT NATIVE PLACE"},
            {"id": 695, "text": "GO TO LIC OFFICE TO SETTLE MONEY BACK POLICY"},
            {"id": 697, "text": "STOMACH PAIN, FEVER"},
            {"id": 698, "text": "MEELADISHAREEF"},
            {"id": 700, "text": "DUE TO PREGNANCY"},
            {"id": 702, "text": "SON'S CATARACT SURGERY"},
            {"id": 703, "text": "GO TO RAMESWARAM TEMPLE WITH FAMILY"},
            {"id": 704, "text": "DOCTOR CONSULTATION"},
            {"id": 705, "text": "NPR CARD PHOTO"},
            {"id": 706, "text": "MEDICAL CHECK UP"},
            {"id": 708, "text": "GO TO HOME"},
            {"id": 709, "text": "PREGNANCY CHECK UP"},
            {"id": 710, "text": "A BABY BORN FOR ME"},
            {"id": 711, "text": "TO ATTEND COLLEGE CONVOCATION AND GET CONVOCATION CERTIFICATE"},
            {"id": 712, "text": "10TH DAY OF RELATIVE"},
            {"id": 713, "text": "FAMILY FUNCTION RELATED TO SISTERS DELIVERY"},
            {"id": 715, "text": "DAUGHTER'S EXAM AT CALICUT"},
            {"id": 716, "text": "THRISSUR POORAM"},
            {"id": 717, "text": "OPERATING MY APPENDIX PROBLEM AS PER DOCTOR INSTRUCTION"},
            {"id": 718, "text": "GO TO DAUGHTER'S SCHOOL MEETING"},
            {"id": 719, "text": "GRANDMOTHER'S AFTER DEATH KARMAS"},
            {"id": 720, "text": "GO TO COLLEGE FOR EXAM"},
            {"id": 722, "text": "NO TRANSPORTATION"},
            {"id": 723, "text": "HARTHAL"},
            {"id": 724, "text": "BUS STRIKE AND HARTAL"},
            {"id": 725, "text": "UNABLE TO REACH DUE TO BUS STRIKE"},
            {"id": 727, "text": "CLASS MATES DEGREE GETOGETHER PARTY COIMBATORE"},
            {"id": 729, "text": "SISTER'S CHILD NAMING CEREMONY"},
            {"id": 732, "text": "FATHER HOSPITALISED"},
            {"id": 733, "text": "POLICE EXAMINATION"},
            {"id": 734, "text": "FRIEND'S MARRIAGE"},
            {"id": 735, "text": "FATHER SICK, HAVE TO TAKE HIM TO DOCTOR"},
            {"id": 736, "text": "TO ATTEND TO AN IMPORTANT DOMESTIC MATTER"},
            {"id": 737, "text": "M.COM SUPPLEMENTARY EXAMS"},
            {"id": 738, "text": "SONS ADMISSION FOR POSTGRADUATION"},
            {"id": 739, "text": "RELATIVE EXPIRED"},
            {"id": 740, "text": "M.P. ELECTION"},
            {"id": 741, "text": "GO TO COLLEGE PG PROJECT PROPOSAL SUBMISSION"},
            {"id": 743, "text": "MONTHLY CHECKUP OF CHILD"},
            {"id": 744, "text": "FATHER RETIREMENT FUNCTION"},
            {"id": 745, "text": "EMPLOYMENT REGISTRATION"},
            {"id": 746, "text": "TO GO TO PANCHAYATH FOR TAKING PHOTO FOR GETTING IDENTITY CARD"},
            {"id": 747, "text": "FEVER AND STOMACH PAIN"},
            {"id": 748, "text": "DEATH ANNIVERSARY OF FATHER"},
            {"id": 749, "text": "GOING TO COURT"},
            {"id": 751, "text": "TO SETTLE MY ACCOUNTS WITH PREVIOUS COMPANY"},
            {"id": 752, "text": "PILGRIMAGE TO VELANKANNI"},
            {"id": 753, "text": "GO TO PANCHAYATH FOR COLLECTING ID PROOF"},
            {"id": 754, "text": "IMPORTANT PERSONAL WORK AT KOLLAM"},
            {"id": 755, "text": "GO TO COLLEGE FOR BA-2 EXAMINATION HINDI-1"},
            {"id": 756, "text": "MY DAUGHTER FIRST BIRTHDAY"},
            {"id": 757, "text": "SISTER IN LAW HOSPITALIZED"},
            {"id": 758, "text": "HOSPITAL"},
            {"id": 759, "text": "PREGNANCY CHECKUP AND TO TAKE TT INJECTION"},
            {"id": 760, "text": "TO ATTEND COURT FOR DIVORCE CASE"},
            {"id": 761, "text": "ARATTUPUZHA POORAM"},
            {"id": 762, "text": "FAMILY FESTIVAL"},
            {"id": 763, "text": "SANJAYANAM OF SISTER IN LAW"},
            {"id": 764, "text": "HUSBAND GO TO ABROAD"},
            {"id": 765, "text": "FOR SHOPPING OF WEDDING ITEMS"},
            {"id": 766, "text": "TO HOSPITALIZE FATHER AND TO CLAIM ESI BENEFITS"},
            {"id": 767, "text": "GO TO TALUK OFFICE FOR SAND PERMISSION PASS"},
            {"id": 768, "text": "ADIYANTHIRAM"},
            {"id": 769, "text": "PERSONAL REASONS"},
            {"id": 770, "text": "RELIGIOUS FUNCTION"},
            {"id": 771, "text": "OWN HOUSE WARMING (GRIHAPRAVESAM WITH POOJA)"},
            {"id": 772, "text": "GO TO UNIVERSITY"},
            {"id": 773, "text": "GO TO TRIVANDRUM"},
            {"id": 774, "text": "GO TO HOME FOR GOOD FRIDAY AND EASTER"},
            {"id": 775, "text": "EXAM PRACTICAL"},
            {"id": 776, "text": "HOSPITALISATION"},
            {"id": 777, "text": "SEVERE HEAD ACHE & VOMITTING"},
            {"id": 779, "text": "GO TO CUSAT"},
            {"id": 780, "text": "TO HOSPITALIZE FATHER AND TO CLAIM ESI BENEFITS"},
            {"id": 781, "text": "GO TO HOME FOR EASTER"},
            {"id": 782, "text": "ATTEND CONVOCATION"},
            {"id": 783, "text": "VISHU"},
            {"id": 784, "text": "ENGAGEMENT OF BROTHER'S SON"},
            {"id": 785, "text": "VISHU"},
            {"id": 786, "text": "41TH DAY OF MY GRANDFATHER'S DEATH"},
            {"id": 787, "text": "GO TO HOME FOR GOOD FRIDAY AND EASTER"},
            {"id": 789, "text": "SISTER HOSPITALISED"},
            {"id": 790, "text": "GOING OUT OF STATION"},
            {"id": 791, "text": "GRANDFATHER DEATH ANNIVERSARY"},
            {"id": 793, "text": "SISTERS OPERATION"},
            {"id": 794, "text": "HUSBAND GOING TO ABROAD"},
            {"id": 795, "text": "TO ARRANGE LOAN FOR SISTER'S MARRIAGE"},
            {"id": 796, "text": "GO TO CHENNAI"},
            {"id": 797, "text": "7TH DAY OF DEATH OF GRANDMOTHER"},
            {"id": 799, "text": "DELIVERY OF WIFE"},
            {"id": 800, "text": "HOLY THURSDAY & GOOD FRIDAY"},
            {"id": 805, "text": "LATE COMING"},
            {"id": 806, "text": "EASTER, HOUSE WARMING"},
            {"id": 807, "text": "CHILD HOSPITALISED"},
            {"id": 808, "text": "GOOD FRIDAY"},
            {"id": 810, "text": "SON'S MARRIAGE"},
            {"id": 811, "text": "BROTHER'S HOUSE WARMING"},
            {"id": 812, "text": "THRISSUR POORAM"},
            {"id": 813, "text": "TO GET INSURANCE CLAIM"},
            {"id": 814, "text": "FOR SISTER'S MARRIAGE RELATED WORKS"},
            {"id": 815, "text": "HEAD ACHE & GIDDINESS"},
            {"id": 816, "text": "DEATH ANNIVERSARY OF UNCLE IN LAW"},
            {"id": 817, "text": "PERSONAL PURPOSE"},
            {"id": 818, "text": "BA EXAMINATION"},
            {"id": 819, "text": "OPERATION FOR MY SON"},
            {"id": 820, "text": "DIARRHOEA & VOMITING"},
            {"id": 822, "text": "MBA EXAM (SEMESTER)"},
            {"id": 823, "text": "GRANDMOTHER NEEDS TO GO TO MEDICAL COLLEGE"},
            {"id": 824, "text": "TO ATTEND FAMILY FUNCTION"},
            {"id": 825, "text": "GO TO HOSPITAL"},
            {"id": 826, "text": "GO TO COLLEGE TO RECEIVE TC & MEDICAL CHECK UP"},
            {"id": 827, "text": "FOR GETTING M.COM SCHOLARSHIP"},
            {"id": 828, "text": "FATHER RETIREMENT FUNCTION"},
            {"id": 829, "text": "FOR THE ARRANGEMENTS OF HOUSE WARMING FEAST"},
            {"id": 830, "text": "OPERATION FOR MY DAUGHTER"},
            {"id": 833, "text": "GO TO DOCTOR CONSULTING FOR EYE PAIN"},
            {"id": 834, "text": "TO GET MY PASSPORT RENEWED"},
            {"id": 835, "text": "TO ATTEND THE GRADUATION DAY PROGRAM HELD IN OUR COLLEGE"},
            {"id": 836, "text": "LEARNER'S TEST FOR DRIVING LICENSE"},
            {"id": 837, "text": "FIRST VISHU AFTER MARRIAGE"},
            {"id": 838, "text": "GO TO TEMPLE WITH MY PARENTS"},
            {"id": 839, "text": "DAUGHTER HOSPITALISED DUE TO FEVER & VOMITTING"},
            {"id": 840, "text": "TO ATTEND COURT FOR DIVORCE CASE"},
            {"id": 841, "text": "PERSONAL"},
            {"id": 842, "text": "SUBMIT HOUSING LOAN DOCUMENTS AND COLLECT FIRST DISBURSEMENT CHEQUE"},
            {"id": 843, "text": "PILGRIMAGE TO PALANI AND MADURAI"},
            {"id": 844, "text": "WORK IN FARM"},
            {"id": 845, "text": "DAUGHTER'S PG ADMISSION WORK AT BANGALORE"},
            {"id": 846, "text": "FESTIVAL"},
            {"id": 847, "text": "TO ATTEND WORK RELATING TO MY SON'S MARRIAGE"},
            {"id": 848, "text": "TO RECEIVE THE PASSPORT"},
            {"id": 849, "text": "IMPORTANT PERSONAL WORK"},
            {"id": 850, "text": "GO TO COLLEGE FOR RECEIVING CERTIFICATE"},
            {"id": 851, "text": "DEATH ANNIVERSARY OF GRANDFATHER"},
            {"id": 852, "text": "APPOINTMENT AT TALUK OFFICE FOR NEW RATION CARD"},
            {"id": 853, "text": "FIRST BIRTHDAY OF SISTER'S DAUGHTER"},
            {"id": 854, "text": "MY SISTER'S MARRIAGE"},
            {"id": 855, "text": "FATHER'S SHRADHAM (DEATH ANNIVERSARY)"},
            {"id": 856, "text": "DEATH ANNIVERSARY OF MY MOTHER"},
            {"id": 857, "text": "CHILDREN HOSPITALISED"},
            {"id": 858, "text": "GO TO UNIVERSITY FOR ATTENDING EXAM"},
            {"id": 860, "text": "FATHER IN LAW HOSPITALISED (ICU) DUE TO AN ACCIDENT"},
            {"id": 861, "text": "TO APPLY POLICE JOB"},
            {"id": 862, "text": "FAMILY FUNCTION"},
            {"id": 863, "text": "PURCHASE OF GOLD FOR MY MARRIAGE"},
            {"id": 864, "text": "EYE PROBLEM, DOCTOR ADVISED TO TAKE REST"},
            {"id": 865, "text": "FAMILY FUNCTION (POOJA)"},
            {"id": 866, "text": "CHILDREN'S CHECK UP"},
            {"id": 867, "text": "SANCHAYANAM OF BROTHER"},
            {"id": 868, "text": "TO GO TO SCHOOL FOR BUYING THE BOOKS AND UNIFORM OF MY SON"},
            {"id": 869, "text": "TO ATTEND WORK RELATING TO MY SON'S MARRIAGE"},
            {"id": 870, "text": "MBA EXAM"},
            {"id": 871, "text": "CAME LATE BEING NOT WELL"},
            {"id": 872, "text": "PG COUNSELING FOR DAUGHTER"},
            {"id": 873, "text": "GRAND DAUGHTER HOSPITALISED"},
            {"id": 874, "text": "DAUGHTER TO JOIN AT MANGALORE FOR MD"},
            {"id": 875, "text": "CONSULT DOCTOR"},
            {"id": 876, "text": "WEEKLY OFF TAKING"},
            {"id": 877, "text": "MEDICAL CHECK UP"},
            {"id": 878, "text": "EAR AND HEAD ACHE"},
            {"id": 879, "text": "KALLIDAL OF NEW HOUSE"},
            {"id": 880, "text": "URGENT WORK AT BANGALORE: DAUGHTER'S MED PG ADMISSION"},
            {"id": 881, "text": "TO GO TO SCHOOL FOR BUYING UNIFORM AND BOOKS OF MY SON"},
            {"id": 882, "text": "ATTEND UNIVERSITY EXAM"},
            {"id": 884, "text": "TO OBTAIN THE MARRIAGE CERTIFICATE"},
            {"id": 885, "text": "SON'S MARRIAGE"},
            {"id": 886, "text": "TRAIN DERAILED SO COULDN'T REACH AT PROPER TIME"},
            {"id": 887, "text": "DEATH KARMA OF GRANDFATHER"},
            {"id": 888, "text": "7TH DAY AFTER DEATH OF GRANDFATHER"},
            {"id": 889, "text": "HARTHAL - CANNOT COME BECAUSE NO TRANSPORT FACILITY"},
            {"id": 890, "text": "SISTER IN LAW'S BETROTHAL"},
            {"id": 891, "text": "MY RECEPTION IN THIRUVANTHAPURAM"},
            {"id": 892, "text": "TO MOOKAMBIKA AND DHARMASTHALA WITH FAMILY"},
            {"id": 893, "text": "ALLERGY DUE TO HEAT"},
            {"id": 894, "text": "HARTAL"},
            {"id": 895, "text": "FOR CHECK UP IN MANIPAL HOSPITAL FOR MY SON"},
            {"id": 897, "text": "GO TO MANIPAL HOSPITAL FOR CHECK UP OF MY SON"},
            {"id": 898, "text": "WIFE SICK"},
            {"id": 899, "text": "PG MED RECOUNSELING FOR DAUGHTER AT BANGALORE"},
            {"id": 900, "text": "HARTHAL"},
            {"id": 901, "text": "HARTAL (NO TRANSPORTATION)"},
            {"id": 903, "text": "DEATH ANNIVERSARY OF GRANDFATHER (SRADHAM)"},
            {"id": 904, "text": "NIECE EXPIRED"},
            {"id": 905, "text": "GO TO PALANI"},
            {"id": 907, "text": "ATTENDING FAMILY FUNCTION AT CALICUT"},
            {"id": 908, "text": "MOTHER-IN-LAW HOSPITALIZED"},
            {"id": 911, "text": "BROTHER AND SISTER MARRIAGE"},
            {"id": 912, "text": "35TH CHARAMA DINAM"},
            {"id": 913, "text": "FAMILY FUNCTION"},
            {"id": 914, "text": "FOR APPLYING ORIGINAL CASTE CERTIFICATE"},
            {"id": 915, "text": "GO TO CHOTTANIKKARA TEMPLE"},
            {"id": 916, "text": "PROPERTY REGISTRATION"},
            {"id": 917, "text": "COUNSELING FOR DAUGHTER FOR PG ADMISSION AT BANGALORE"},
            {"id": 918, "text": "PERSONAL WORK AT MANGALORE"},
            {"id": 919, "text": "FRIEND'S MARRIAGE"},
            {"id": 920, "text": "CA FINAL EXAM"},
            {"id": 922, "text": "FOR VOTING PURPOSE OF GRAM PANCHAYATH"},
            {"id": 923, "text": "SISTER'S ENGAGEMENT"},
            {"id": 924, "text": "GOING TO HIGH COURT TO ENROLL LLB CERTIFICATE"},
            {"id": 925, "text": "BROTHER'S DAUGHTER'S ENGAGEMENT"},
            {"id": 926, "text": "MARRIAGE REGISTRATION AT MUNICIPAL OFFICE"},
            {"id": 927, "text": "GO TO PANCHAYATH FOR IDENTITY VERIFICATION"},
            {"id": 928, "text": "FOR VOTING PURPOSE OF GRAM PANCHAYATH"},
            {"id": 929, "text": "GO TO EXAMINATION"},
            {"id": 930, "text": "UNDERGONE SURGERY"},
            {"id": 931, "text": "PREGNANCY CHECK UP & SCANNING"},
            {"id": 932, "text": "TO ATTEND TO AN URGENT PERSONAL WORK"},
            {"id": 933, "text": "MY APPENDIX OPERATION AS PER DOCTOR INSTRUCTION"},
            {"id": 934, "text": "DAUGHTER'S MARRIAGE"},
            {"id": 935, "text": "MAASIKAM (PERIODICAL MONTHLY DEATH CEREMONY) OF MY UNCLE"},
            {"id": 936, "text": "MBA EXAMINATION"},
            {"id": 937, "text": "MEDICAL CHECKUP FOR SON"},
            {"id": 938, "text": "GO TO NAVODAYA SCHOOL FOR SIGNING PROGRESS REPORT"},
            {"id": 939, "text": "OWN GRANDFATHER DEATH ANNIVERSARY"},
            {"id": 940, "text": "VILLAGE PANCHAYAT ELECTION IN MY VILLAGE"},
            {"id": 941, "text": "BROTHER MARRIAGE"},
            {"id": 942, "text": "GO TO NATIVE PLACE"},
            {"id": 943, "text": "FEVER & VOMITTING"},
            {"id": 944, "text": "FAMILY FUNCTION"},
            {"id": 945, "text": "11TH DEATH DAY OF MY OWN SISTER"},
            {"id": 946, "text": "TO PURCHASE DRESS FOR OWN MARRIAGE"},
            {"id": 947, "text": "INEVITABLE PERSONAL WORK"},
            {"id": 948, "text": "WENT TO ENROLL BAR COUNCIL LLB CERTIFICATE"},
            {"id": 949, "text": "OWN GRANDFATHER DEATH ANNIVERSARY"},
            {"id": 950, "text": "GRANDFATHER'S TREATMENT (OPERATION) AT COIMBATORE"},
            {"id": 952, "text": "GO TO GURUVAYOOR TEMPLE FOR ANNAPRASHAM OF MY DAUGHTER"},
            {"id": 953, "text": "UNCLE'S DEATH"},
            {"id": 954, "text": "MAINTENANCE OF HOUSE"},
            {"id": 955, "text": "FAMILY MATTERS"},
            {"id": 956, "text": "TO PANCHAYATH TO GET SANCTION OF HOME LOAN APPLIED"},
            {"id": 958, "text": "KEG SPRAIN"},
            {"id": 959, "text": "LEG SPRAIN"},
            {"id": 960, "text": "SEVERE DENTAL PAIN AND HEAD ACHE"},
            {"id": 962, "text": "SWELLING ON THE LEG AND UNABLE TO WALK"},
            {"id": 963, "text": "HUSBAND'S BROTHER EXPIRED"},
            {"id": 964, "text": "COUSIN BROTHER EXPIRED"},
            {"id": 965, "text": "GO TO CHAVAKKAD TALUK OFFICE"},
            {"id": 968, "text": "OWN GRANDFATHER DEATH ANNIVERSARY IN ANDHRA PRADESH"},
            {"id": 969, "text": "FAMILY FUNCTION AT BANGALORE"},
            {"id": 970, "text": "GO TO COLLEGE FOR MBA CERTIFICATE APPLICATION"},
            {"id": 971, "text": "FOR MOTHER'S MEDICAL CHECK UP"},
            {"id": 972, "text": "VIDHYARABHAM OF SON"},
            {"id": 973, "text": "SISTER'S ENGAGEMENT"},
            {"id": 974, "text": "OWN MATERNAL GRANDFATHER DEATH FUNCTION"},
            {"id": 975, "text": "FOR APPLYING MARRIAGE CERTIFICATE"},
            {"id": 976, "text": "GOING TO MOOKAMBIKA TEMPLE"},
            {"id": 977, "text": "LEG SPRAIN"},
            {"id": 978, "text": "REGISTRATION OF OWN PROPERTY"},
            {"id": 979, "text": "OFFERING AT THIRUVILWAMALA TEMPLE"},
            {"id": 981, "text": "SCHOOL ADMISSION OF SON"},
            {"id": 982, "text": "BROTHER'S MARRIAGE"},
            {"id": 983, "text": "HOUSE WARMING"},
            {"id": 984, "text": "LOCAL HARTHAL"},
            {"id": 985, "text": "SANJAYANAM"},
            {"id": 986, "text": "DAUGHTER HOSPITALISED"},
            {"id": 987, "text": "FIRST DAY AT SCHOOL OF MY DAUGHTER"},
            {"id": 988, "text": "GO TO COLLEGE FOR PROJECT SUBMISSION"},
            {"id": 989, "text": "TO CONSULT ADVOCATE"},
            {"id": 990, "text": "B.COM 2 YEAR SEMESTER EXAM"},
            {"id": 991, "text": "FOR COLLEGE ADMISSION TO DAUGHTER"},
            {"id": 992, "text": "ATTEND THE MARRIAGE FUNCTION"},
            {"id": 994, "text": "GO TO UNIVERSITY FOR GET BACK MY CERTIFICATES"},
            {"id": 995, "text": "GO TO COLLEGE FOR PROJECT COMPLETION"},
            {"id": 996, "text": "NON MARKING EVENING"},
            {"id": 997, "text": "HARTAL - HOME IS FAR AWAY FROM BRANCH"},
            {"id": 998, "text": "REGISTRATION OF PROPERTY"},
            {"id": 999, "text": "WEEKLY HOLY DAY / OFF"},
            {"id": 1000, "text": "SON RETURNING ABROAD"},
            {"id": 1001, "text": "RECTIFY PENDING ENTRIES"},
            {"id": 1002, "text": "FATHER'S EYE SURGERY"},
            {"id": 1003, "text": "FATHER'S EYE OPERATION"},
            {"id": 1004, "text": "ACCOMPANY WIFE TO TRIVANDRUM FOR INTERVIEW"},
            {"id": 1005, "text": "DRIVING TEST"},
            {"id": 1007, "text": "GO TO VILLAGE OFFICE FOR INCOME CERTIFICATE"},
            {"id": 1010, "text": "ACCOMPANY DAUGHTER TO PARTICIPATE DISTRICT KALOTSAV"},
            {"id": 1012, "text": "10TH DAY OF DEATH OF BROTHER"},
            {"id": 1013, "text": "40TH DAY OF DEATH OF BROTHER"},
            {"id": 1015, "text": "ELECTION"},
            {"id": 1016, "text": "DOCTOR'S CONSULTATION OF MY DAUGHTER"},
            {"id": 1017, "text": "TRAIN CANCELLED/DIVERTED"},
            {"id": 1018, "text": "TOO LATE"},
            {"id": 1019, "text": "GRANDMOTHER'S DEATH CEREMONY"},
            {"id": 1020, "text": "SUNNATH KALYANAM"},
            {"id": 1021, "text": "KETTUNIRA (SABARIMALA) AT HOUSE"},
            {"id": 1023, "text": "UNION STRIKE"},
            {"id": 1024, "text": "AS PER THE INSTRUCTION FROM HOD"},
            {"id": 1025, "text": "LOCK DOWN COVID-19"},
            {"id": 1026, "text": "QUARANTINE"},
            {"id": 1027, "text": "EARLY GOING FORGOT TO APPLY"},
            {"id": 1028, "text": "COUSIN'S MARRIAGE"},
            {"id": 1029, "text": "WENT TO SABARIMALA"},
            {"id": 1030, "text": "GO TO HOSPITAL FOR MONTHLY CHECK UP FOR WIFE"},
            {"id": 1031, "text": "VEHICLE DAMAGE"},
            {"id": 1032, "text": "HOUSE SHIFTING"},
            {"id": 1033, "text": "WIFE DUE DATE"},
            {"id": 1034, "text": "NON MARKING"},
            {"id": 1035, "text": "NON PUNCHING"},
            {"id": 1036, "text": "DISCHARGE OF BROTHER"},
            {"id": 1037, "text": "BACK PAIN"},
            {"id": 1040, "text": "GO TO FAMILY TOUR"},
            {"id": 1041, "text": "GOING TO ABROAD"},
            {"id": 1042, "text": "NON MARKING MORNING"},
            {"id": 1043, "text": "OUT-OF-TOWN"},
            {"id": 1044, "text": "GURUVAYUR TEMPLE VISIT"},
            {"id": 1048, "text": "GOING TO KOTTIYUR MAHADEVA TEMPLE"},
            {"id": 1049, "text": "SON'S FIRST DAY AT SCHOOL"},
            {"id": 1050, "text": "HUSBAND GOING ABROAD"},
            {"id": 1051, "text": "TO TAKE MY SON'S MANDATORY SIX-MONTH GAP VITAMIN"},
            {"id": 1052, "text": "10TH DAY OF DEATH OF FATHER"},
            {"id": 1057, "text": "FORGOT TO PUNCH EVENING"},
            {"id": 1060, "text": "ACCOMPANYING MY FATHER FOR HIS MEDICAL CHECK-UP"},
            {"id": 1061, "text": "MOTHER-IN-LAW MET WITH AN ACCIDENT"},
            {"id": 1062, "text": "IN HOSPITAL AS A BYSTANDER SUPPORT"},
            {"id": 1063, "text": "HARTHAL"},
        ],
    },

    7: {
        "name": "HEALTH RELATED ISSUES (self)",
        "reasons": [
            {"id": 1,  "text": "HEAD ACHE"},
            {"id": 2,  "text": "STOMACH PAIN"},
            {"id": 3,  "text": "BACK PAIN"},
            {"id": 4,  "text": "LEG PAIN"},
            {"id": 5,  "text": "EYE PAIN"},
            {"id": 6,  "text": "FEVER"},
            {"id": 7,  "text": "EAR PAIN"},
            {"id": 8,  "text": "CHEST PAIN"},
            {"id": 9,  "text": "DYSENTERY"},
            {"id": 10, "text": "JAUNDICE"},
            {"id": 11, "text": "GIDDINESS / DIZZINESS"},
            {"id": 12, "text": "VIRAL FEVER"},
            {"id": 13, "text": "VOMITTING"},
            {"id": 14, "text": "BED REST"},
            {"id": 15, "text": "CHICKENPOX"},
            {"id": 16, "text": "MEDICAL CHECK UP"},
            {"id": 17, "text": "MIGRAINE"},
            {"id": 18, "text": "BURNED INJURY"},
            {"id": 19, "text": "ACCIDENT"},
            {"id": 20, "text": "ASTHMA"},
            {"id": 21, "text": "SURGERY AND BED REST"},
            {"id": 22, "text": "ABORTION AND BED REST"},
            {"id": 23, "text": "SCANNING"},
            {"id": 24, "text": "URINARY INFECTION"},
            {"id": 25, "text": "LOW B.P"},
            {"id": 26, "text": "PRE SURGERY TEST"},
            {"id": 27, "text": "EYE INFECTION"},
            {"id": 28, "text": "ENDOSCOPIC SINUS SURGERY"},
            {"id": 29, "text": "LEFT FROM OFFICE"},
            {"id": 30, "text": "FOOD POISON"},
            {"id": 31, "text": "INFERTILITY TREATMENT"},
            {"id": 32, "text": "THROAT PAIN"},
            {"id": 33, "text": "TEETH PAIN"},
            {"id": 34, "text": "WHEEZING"},
            {"id": 35, "text": "FOETEL ECHO TEST & CARDIO THORACIC"},
            {"id": 36, "text": "CONSULT DOCTOR"},
            {"id": 37, "text": "SPONDYLOSIS (NECK PAIN)"},
            {"id": 38, "text": "COVID-19"},
            {"id": 39, "text": "CONTAINMENT ZONE"},
            {"id": 40, "text": "SELF QUARANTINE"},
            {"id": 42, "text": "COVID POSITIVE"},
            {"id": 43, "text": "SURGERY"},
            {"id": 44, "text": "HAIR TRANSPLANTATION PROCEDURE"},
            {"id": 45, "text": "PERIOD PAIN"},
            {"id": 1044, "text": "GASTRIC PROBLEM"},
            {"id": 1045, "text": "3rd Month Pregnancy NT Scan"},
            {"id": 1046, "text": "5TH MONTH ANOMALY SCANNING"},
            {"id": 1047, "text": "GO TO HOSPITAL"},
            {"id": 1048, "text": "FETAL PULSE EVALUATION"},
            {"id": 1049, "text": "BLOOD TEST"},
            {"id": 1050, "text": "9th Month Scanning"},
            {"id": 1051, "text": "LLB EXAMINATION"},
            {"id": 1052, "text": "MATERNITY LEAVE"},
        ],
    },

    8: {
        "name": "ENGAGEMENT",
        "reasons": [
            {"id": 1, "text": "OWN ENGAGEMENT"},
            {"id": 2, "text": "SISTER'S ENGAGEMENT"},
            {"id": 3, "text": "BROTHER'S ENGAGEMENT"},
            {"id": 4, "text": "SISTER IN LAW'S ENGAGEMENT"},
            {"id": 5, "text": "BROTHER IN LAW'S ENGAGEMENT"},
            {"id": 6, "text": "RELATIVE'S ENGAGEMENT"},
            {"id": 7, "text": "FRIEND'S ENGAGEMENT"},
            {"id": 8, "text": "COUSIN'S ENGAGEMENT"},
            {"id": 9, "text": "DAUGHTER'S ENGAGEMENT"},
        ],
    },

    9: {
        "name": "OTHER COMMON REASONS",
        "reasons": [
            {"id": 1,  "text": "41ST DAY OF MY FATHERS DEATH"},
            {"id": 2,  "text": "41ST DAY OF MY MOTHERS DEATH"},
            {"id": 3,  "text": "BANK PURPOSE"},
            {"id": 4,  "text": "BUS STRIKE"},
            {"id": 5,  "text": "GO TO TEMPLE"},
            {"id": 6,  "text": "GO TO HOME"},
            {"id": 7,  "text": "FUNERAL OF GRANDMOTHER"},
            {"id": 8,  "text": "DAUGHTER'S SCHOOL ADMISSION"},
            {"id": 9,  "text": "SONS SCHOOL ADMISSION"},
            {"id": 10, "text": "HUSBAND COMING FROM ABROAD"},
            {"id": 11, "text": "11th DAY OF MY MOTHERS DEATH"},
            {"id": 12, "text": "ELECTION"},
            {"id": 13, "text": "GO TO HOSPITAL"},
            {"id": 14, "text": "GO TO SABARIMALA"},
            {"id": 15, "text": "GO TO HUSBAND'S HOUSE AT IDUKKI"},
            {"id": 16, "text": "GO TO SABARIMALA"},
            {"id": 17, "text": "KETTUNIRA AT HOME"},
            {"id": 18, "text": "WEEKLY OFF PROBLEM"},
            {"id": 19, "text": "GO TO ESI HOSPITAL"},
            {"id": 20, "text": "GO TO ELECTRICITY OFFICE"},
            {"id": 21, "text": "TO TAKING BIRTH CERTIFICATE"},
            {"id": 22, "text": "FOR REGISTERING BIRTH CERTIFICATE OF DAUGHTER"},
            {"id": 23, "text": "GO TO COLLECT ELECTRICITY BILL"},
            {"id": 24, "text": "GO TO EDUCATIONAL DEPARTMENT"},
            {"id": 25, "text": "TO SEE NEW BORN BABY"},
            {"id": 26, "text": "TO GO PASSPORT OFFICE (EKM)"},
            {"id": 27, "text": "SISTER HOSPITALIZED"},
            {"id": 28, "text": "SON COMING FROM ABROAD"},
            {"id": 29, "text": "WIFE'S SURGERY (TUBAL LIGATION)"},
            {"id": 30, "text": "GO TO MOOKAMBIKA TEMPLE"},
            {"id": 31, "text": "SCHOOL ADMISSION OF SON"},
            {"id": 32, "text": "RECTIFY PENDING ENTRIES"},
            {"id": 33, "text": "HOUSE MAINTENANCE WORK"},
            {"id": 34, "text": "AADHAAR CARD PHOTO"},
            {"id": 35, "text": "ACCOMPANY DAUGHTER FOR EXAM AT CALICUT"},
            {"id": 36, "text": "FAMILY TOUR"},
            {"id": 37, "text": "ACCOMPANY FATHER-IN-LAW TO HOSPITAL"},
            {"id": 38, "text": "HOME QUARANTINE"},
            {"id": 39, "text": "DEATH ANNIVERSARY OF GRANDMOTHER"},
            {"id": 40, "text": "FUNERAL OF RELATIVE"},
            {"id": 41, "text": "SCHOOL OPENING"},
            {"id": 42, "text": "THREE DAYS LATE"},
            {"id": 43, "text": "16TH DAY OF DEMISE"},
            {"id": 44, "text": "PTA MEETING"},
            {"id": 45, "text": "DEATH OF FATHER'S BROTHER"},
            {"id": 46, "text": "CELEBRATE MY SON'S BIRTHDAY WITH FAMILY"},
        ],
    },

    10: {
        "name": "FESTIVAL",
        "reasons": [
            {"id": 1,  "text": "ASHTAMI ROHINI"},
            {"id": 2,  "text": "DEEPAVALI"},
            {"id": 3,  "text": "LOCAL FESTIVAL"},
            {"id": 4,  "text": "CHRISTMAS"},
            {"id": 5,  "text": "BAKRID"},
            {"id": 6,  "text": "ATTUKAL PONGALA"},
            {"id": 7,  "text": "NABI DHINAM"},
            {"id": 8,  "text": "EASTER"},
            {"id": 9,  "text": "AADI FESTIVAL"},
            {"id": 10, "text": "CHATHAYAM"},
            {"id": 11, "text": "KODUNGALLUR BHARANI"},
            {"id": 12, "text": "THALAPPOLI"},
            {"id": 13, "text": "GURUVAYOOR EKADHASI"},
            {"id": 14, "text": "VINAYAKA CHATURTHI"},
            {"id": 15, "text": "GURU POORNIMA"},
            {"id": 16, "text": "VIJAYA DASHAMI"},
            {"id": 17, "text": "THIRUVONAM"},
            {"id": 18, "text": "MAKARA VILAKKU"},
        ],
    },

    11: {
        "name": "EXAMS AND SCHOOL",
        "reasons": [
            {"id": 1,   "text": "ACCOMPANY DAUGHTER TO NAVODAYA SCHOOL"},
            {"id": 2,   "text": "ADMISSION FOR MY SON"},
            {"id": 3,   "text": "DRIVING TEST"},
            {"id": 4,   "text": "REGISTRATION FOR DEGREE SUNDAY BATCH"},
            {"id": 5,   "text": "DAUGHTER'S COLLEGE ADMISSION"},
            {"id": 6,   "text": "ACCOMPANYING DAUGHTER TO KOLLAM TKM ENGINEERING COLLEGE"},
            {"id": 7,   "text": "TO ATTEND TRAINING"},
            {"id": 8,   "text": "CHILD'S FIRST DAY IN SCHOOL"},
            {"id": 9,   "text": "CHILD'S SCHOOL ANNUAL DAY"},
            {"id": 10,  "text": "CHILD'S SCHOOL ADMISSION"},
            {"id": 11,  "text": "PLUS 2 EXAMINATION"},
            {"id": 12,  "text": "LLB EXAM"},
            {"id": 13,  "text": "MBA EXAMINATION"},
            {"id": 999, "text": "AADHAAR CARD PHOTO"},
            {"id": 1015, "text": "FATHER'S SURGERY"},
            {"id": 1231, "text": "HOSPITALIZED"},
            {"id": 1232, "text": "HUSBAND HOSPITALISED DUE TO VIRAL FEVER"},
        ],
    },

    12: {
        "name": "ATHAR CARD PHOTO",
        "reasons": [
            {"id": 1201, "text": "Aadhaar card enrollment or update"},
            {"id": 1202, "text": "Aadhaar biometric update"},
            {"id": 1203, "text": "Aadhaar photo correction"},
        ],
    },

    13: {
        "name": "Foetel Echo test & Cardiothoracic test",
        "reasons": [
            {"id": 1301, "text": "Foetal echo test for pregnancy"},
            {"id": 1302, "text": "Cardiothoracic test or heart check-up"},
            {"id": 1303, "text": "Prenatal medical test"},
            {"id": 1304, "text": "Cardiac evaluation or ECG"},
        ],
    },

    14: {
        "name": "SURGERY",
        "reasons": [
            {"id": 1401, "text": "Undergoing surgery"},
            {"id": 1402, "text": "Post surgery recovery"},
            {"id": 1403, "text": "Minor surgical procedure"},
            {"id": 1404, "text": "Planned operation"},
            {"id": 1405, "text": "Emergency surgery"},
        ],
    },

    15: {
        "name": "HOSPITAL",
        "reasons": [
            {"id": 1501, "text": "Hospitalized for treatment"},
            {"id": 1502, "text": "Hospital visit for tests"},
            {"id": 1503, "text": "Admitted for observation"},
            {"id": 1504, "text": "Accompanying family member to hospital"},
            {"id": 1505, "text": "Emergency hospital visit"},
            {"id": 1506, "text": "Outpatient department visit"},
        ],
    },

    16: {
        "name": "I V D P Lumbar Spondylosis",
        "reasons": [
            {"id": 1601, "text": "IVDP lumbar spondylosis treatment"},
            {"id": 1602, "text": "Spinal disc pain or lower back issue"},
            {"id": 1603, "text": "Physiotherapy for back pain"},
            {"id": 1604, "text": "Neurological treatment for spine"},
        ],
    },

    17: {
        "name": "FORGOT TO PUNCH (EVENING)",
        "reasons": [
            {"id": 1701, "text": "Forgot to punch out in evening"},
            {"id": 1702, "text": "Missed biometric punch out"},
            {"id": 1703, "text": "Evening attendance punch missed"},
        ],
    },

    18: {
        "name": "FORGOT TO PUNCH (MORNING)",
        "reasons": [
            {"id": 1801, "text": "Forgot to punch in morning"},
            {"id": 1802, "text": "Missed biometric punch in"},
            {"id": 1803, "text": "Morning attendance punch missed"},
        ],
    },

    19: {
        "name": "OtherReasonsNotIncludedinList",
        "reasons": [
            {"id": 1901, "text": "Reason not listed in available options"},
            {"id": 1902, "text": "Custom personal reason"},
            {"id": 1903, "text": "Other unlisted leave reason"},
        ],
    },
}

PKL_PATH = "reasons_index.pkl"
MODEL    = "all-MiniLM-L6-v2"


# ─────────────────────────────────────────────────────────────────────────────
# CHECKSUM
# ─────────────────────────────────────────────────────────────────────────────
def _checksum() -> str:
    parts = []
    for cat_id, cat in sorted(LEAVE_REASON_DATA.items()):
        for r in cat["reasons"]:
            parts.append(f"{cat_id}:{r['id']}:{r['text']}")
    return hashlib.md5("|".join(parts).encode()).hexdigest()


# ─────────────────────────────────────────────────────────────────────────────
# BUILD
# ─────────────────────────────────────────────────────────────────────────────
def build():
    print(f"Loading model: {MODEL} ...")
    model = SentenceTransformer(MODEL)

    all_texts = []
    meta      = []  # (cat_id, reason_id, text)

    for cat_id, cat in LEAVE_REASON_DATA.items():
        for r in cat["reasons"]:
            all_texts.append(r["text"])
            meta.append((cat_id, r["id"], r["text"]))

    print(f"Embedding {len(all_texts)} reasons across {len(LEAVE_REASON_DATA)} categories ...")
    vecs = model.encode(all_texts, convert_to_numpy=True).tolist()

    # Build index  { category_id: [ {id, text, vec} ] }
    index: dict[int, list[dict]] = {}
    for (cat_id, rid, text), vec in zip(meta, vecs):
        index.setdefault(cat_id, []).append(
            {"id": rid, "text": text, "vec": vec}
        )

    payload = {
        "checksum": _checksum(),
        "engine":   "sentence-transformers",
        "model":    MODEL,
        "index":    index,
    }
    with open(PKL_PATH, "wb") as f:
        pickle.dump(payload, f)

    print(f"\n✔  Saved → {PKL_PATH}")
    print(f"   Total reasons embedded : {len(all_texts)}")
    print(f"   Total categories       : {len(index)}")
    print()
    for cat_id, entries in index.items():
        name = LEAVE_REASON_DATA[cat_id]["name"]
        print(f"   [{cat_id:>2}] {name:<50} — {len(entries)} reasons")


if __name__ == "__main__":
    build()